// The imagesdir attribute is only needed to display images during offline editing. Antora neglects the attribute.
:imagesdir: ../images

[[_drssfeedurldetails]]
= RSS URL Details 
(((RSS URL Details))) 

The IKAN ALM URL has the following structure: 

_protocol://almhost:almhostport/alm/displayRss.actionrequestparams_

This is equal to the value of the IKAN ALM URL as set in <<GlobAdm_System.adoc#_globadm_system_settings,System Settings>> :

* "`protocol`" = http or https
* "`almhost:almhostport`" = the IKAN ALM server domain,e.g., localhost:8080
* "`requestparams`" = 


The list of (optional) criteria will be added, separated with an "`&`" sign.
The following table gives you an overview of the optional criteria. 

[cols="1,3", frame="topbot", options="header"]
|===
| Optional Criteria
| Description

|Title=value
a|This is the title that will be shown in the RSS Feed.

If it is not provided, it will be set automatically when the RSS feed is constructed.
This way it is possible to place more than one IKAN ALM RSS Feed in the RSS reader (e.g., for different projects).

[NOTE]
====
Whitespace in the request can be provided via a "`+`" sign.
====

|projectName=value
|The Project Name. 

For example: projectName=DEMOCVS, or projectName=D*

|status=value
a|The Level Request status.
Multiple statuses may be provided.

For example: statuses=6&statuses=7

Valid statuses are  : 

* 0 : Unknown 
* 1 : Awaiting requested Date/time
* 2 : Awaiting Approval
* 3 : Rejected
* 4 : Run
* 5 : Fail
* 6 : Success
* 7 : Warning
* 8 : Cancelled
* 9 : Aborting
* 10 : Aborted

|projectStreamBuildPrefix=value
|The Project Stream Build Prefix as defined in a Project Stream.

For example: ProjectStreamBuildPrefix=1

|projectStreamBuildSuffix=value
|The Project Stream Build Suffix as defined in a Project Stream.

For example: ProjectStreamBuildSuffix=1

|levelName
|The level name.

For example:levelName=contbuild

|levelType=value
a|The level type.

For example: levelType=0

Valid values are :

* 0 : Build
* 1 : Test
* 2 : Production

|lang=value
|Valid locale indicating the user`'s language (default = none = en).

For example: lang=en, lang=de, lang=fr (the three currently supported languages in IKAN ALM)
|===


Valid sample URLs:

\http://localhost:8080/alm/displayRss.action

\http://localhost:8080/alm/displayRss.action?lang=de

\https://pe4600:8080/alm/displayRss.action?projectName=DEMOCVS&projectStreamBuildPrefix=1&projectStreamBuildSuffix=1&levelType=0&lang=fr

\https://pe4600:8080/alm/displayRss.action?projectName=DEMOCVS&projectStreamBuildPrefix=1&projectStreamBuildSuffix=1&levelType=0&title=IKAN ALM+builds+in+project+DEMOCVS

