
[[_resources]]
== Resources

[[_authentication_resource]]
===  Authentication
This resource represents Authentication. Use it to obtain authentication info, authenticate or log out from Kobee.


[[_loginusingpost]]
==== Post an Authentication View for login
....
POST /auth
....


===== Description
Post an Authentication View containing filled in username and password. If the credentials match those of the connected Security System, the user is logged in and gets a Session.
 The response will contain some information about this session of the user.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**xmlAuthenticationView** +
__required__|The Authentication View containing the credentials (username and password) of the user that tries to log in.|<<RESTAPI_Definitions.adoc#_xmlauthenticationview,XmlAuthenticationView>>
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**201**|Created|<<RESTAPI_Definitions.adoc#_xmlauthenticationview,XmlAuthenticationView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/auth
----


====== Request body
[source,json]
----
{
  "password" : "user",
  "username" : "user"
}
----


===== Example HTTP response

====== Response 201
[source,json]
----
{
  "email-address" : "user@example.com",
  "is-administrator" : false,
  "is-reserved-user" : true,
  "locale" : "en",
  "login-date" : "2019-11-22T08:17:39",
  "login-host-ip" : "0:0:0:0:0:0:0:1",
  "login-hostname" : "localhost",
  "password" : "user",
  "user-fullname" : "User",
  "username" : "user"
}
----


[[_getemptyauthenticationviewusingget]]
==== Get an Authentication View
....
GET /auth
....


===== Description
Get an Authentication View. If you do not have a valid session, it will return an empty View that can be filled in and posted to authenticate to Kobee. If you have a valid session, it will return information about this session.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlauthenticationview,XmlAuthenticationView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/auth
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "password" : "user",
  "username" : "user"
}
----


[[_logoutusingdelete]]
==== Delete Session
....
DELETE /auth
....


===== Description
Deletes the Authentication Session of the current user, logging him/her out of Kobee.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|No Content
|**204**|No Content|No Content
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|===


===== Example HTTP request

====== Request path
----
/auth
----


[[_approvals_resource]]
===  Approvals
This resource represents Approvals. Use it to obtain details of the existing Approvals and approve/reject them.


[[_getallapprovalsusingget]]
==== Get Approvals paginated
....
GET /approvals
....


===== Description
Get a paginated list of Approvals, optionally filtered by approvalstatus or whether the approval can be/has been approved by the current user (myapprovals parameter).
 Sorting can be done by:
* levelrequest.oid;
* levelapproval.status;
* levelapproval.type;
* project.name;
* scmlevel.name;
* levelrequest.status;
* levelrequest.vcrtag;
* levelrequest.creationdatetime;
* levelrequest.requesteddatetime.

The Outstanding Approvals can be obtained by setting following parameters: myapprovals=true and approvalstatuses=1.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**approvalstatuses** +
__optional__|The status to filter the Approvals by. Allowed values are 0 to 6, inclusive.
Multiple values allowed when separated by commas (not functional in the try it out input).|integer (int32)|
|**Query**|**approvedbyuserid** +
__optional__|The User ID to filter the Approvals by, based on who approved or rejected the Approval.|string|
|**Query**|**myapprovals** +
__optional__|Whether to show only the approvals the current user has/had approval rights on, or (value false) to show all approvals.|enum (true, on, yes, 1, false, off, no, 0)|
|**Query**|**page** +
__optional__|The page to retrieve, defaulted to 1.|string|`"1"`
|**Query**|**pagesize** +
__optional__|The page size to retrieve, defaulted to 10.|string|`"10"`
|**Query**|**sortcolumn** +
__optional__|The attribute to sort the result by, check the endpoint description for the possible values.|string|
|**Query**|**sortdirection** +
__optional__|The sort direction to order the result, defaulted to ascending.|enum (desc, descending, true, asc, ascending, false)|`"asc"`
|**Query**|**view** +
__optional__|Whether to show only a list of Approval links or also all the Approval attributes.|enum (links, all)|
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlapprovalviewlist,XmlApprovalViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/approvals
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "approvals" : [ {
    "approve-datetime" : "2019-11-22T08:17:39",
    "approved-by-user" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "id" : "urn:alm:viewName:1:1",
    "level-id" : "1",
    "levelrequest" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "projectstream" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "reason" : "Approved By User X",
    "sequence-number" : 1,
    "status" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "type" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "usergroup" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    }
  } ],
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0
}
----


[[_getapprovalbyoidusingget]]
==== Get Approval
....
GET /approvals/{id}
....


===== Description
Get the details of a specific Approval.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Approval to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlapprovalview,XmlApprovalView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/approvals/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "approve-datetime" : "2019-11-22T08:17:39",
  "approved-by-user" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "id" : "urn:alm:viewName:1:1",
  "level-id" : "1",
  "levelrequest" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "projectstream" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "reason" : "Approved By User X",
  "sequence-number" : 1,
  "status" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "type" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "usergroup" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  }
}
----


[[_updateapprovalusingpatch]]
==== Approve or reject Approval
....
PATCH /approvals/{id}
....


===== Description
Approve or reject a specific Approval.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**If-Match** +
__required__|A header parameter that should contain the value of the latest ETag header for the Approval to approve or reject.
 The latest ETag can be retrieved by a Get Approval action.|string
|**Path**|**id** +
__required__|The identifier of the Approval to approve or reject.|integer (int32)
|**Body**|**approveView** +
__required__|The view to submit in order to approve or reject the Approval.|<<RESTAPI_Definitions.adoc#_xmlapprovepatchview,XmlApprovePatchView>>
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlapprovalview,XmlApprovalView>>
|**204**|No Content|No Content
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|===


===== Example HTTP request

====== Request path
----
/approvals/1
----


====== Request header
[source,json]
----
"c3fc3a7f25d734b03e686e4d6938c49f"
----


====== Request body
[source,json]
----
{
  "approve" : true,
  "reason" : "Approved by User X"
}
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "approve-datetime" : "2019-11-22T08:17:39",
  "approved-by-user" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "id" : "urn:alm:viewName:1:1",
  "level-id" : "1",
  "levelrequest" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "projectstream" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "reason" : "Approved By User X",
  "sequence-number" : 1,
  "status" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "type" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "usergroup" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  }
}
----


[[_builds_resource]]
===  Builds
This resource represents Builds. Use it to obtain details of the existing Builds.


[[_getlevelrequestbuildphasesbyoidusingget]]
==== Get Phases of Build
....
GET /builds/{buildId}/phases
....


===== Description
Get the Phases of a specific Build.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**buildId** +
__required__|The identifier of the Build to retrieve the Phases for.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlphaselogviewlist,XmlPhaseLogViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/builds/1/phases
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "phases" : [ {
    "display-name" : "Execute Script Phase",
    "duration" : 178890402,
    "end-datetime" : "2019-11-22T08:17:50",
    "formattingData" : "/xslt/ant/log.xsl",
    "id" : "urn:alm:viewName:1:1",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "log-format" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "message" : "Message",
    "phase-name" : "be.ikan.scm4all.phases.core.executeScript",
    "phase-version" : "5.9.0",
    "stackTrace" : "Stack trace",
    "start-datetime" : "2019-11-22T08:17:39",
    "status" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    }
  } ],
  "total" : 0
}
----


[[_constants_resource]]
===  Constants
This resource represents Constants. Use it to obtain details of constants used in Kobee.


[[_getallapprovalstatusesusingget]]
==== Get Approval Statuses
....
GET /constants/approvals/approvalstatuses
....


===== Description
Get all valid values for the Status field for Approvals.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlapprovalstatuslist,XmlApprovalStatusList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/approvals/approvalstatuses
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "approvalstatuses" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ],
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ]
}
----


[[_getapprovalstatusbyidusingget]]
==== Get Approval Status by Identifier
....
GET /constants/approvals/approvalstatuses/{id}
....


===== Description
Get a single valid Status value for Approvals by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlapprovalstatus,XmlApprovalStatus>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/approvals/approvalstatuses/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getallapprovaltypesusingget]]
==== Get Approval Types
....
GET /constants/approvals/approvaltypes
....


===== Description
Get all valid values for the Type field for Approvals.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlapprovaltypelist,XmlApprovalTypeList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/approvals/approvaltypes
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "approvaltypes" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ],
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ]
}
----


[[_getapprovaltypebyidusingget]]
==== Get Approval Type by Identifier
....
GET /constants/approvals/approvaltypes/{id}
....


===== Description
Get a single valid Type value for Approvals by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlapprovaltype,XmlApprovalType>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/approvals/approvaltypes/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getallbuildarchivestatusesusingget]]
==== Get Build Archive Statuses
....
GET /constants/builds/archivestatuses
....


===== Description
Get all valid values for the Archive Status field for Builds.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlbuildarchivestatuslist,XmlBuildArchiveStatusList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/builds/archivestatuses
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "archivestatuses" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ],
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ]
}
----


[[_getbuildarchivestatusbyidusingget]]
==== Get Build Archive Status by Identifier
....
GET /constants/builds/archivestatuses/{id}
....


===== Description
Get a single valid Archive Status value for Builds by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlbuildarchivestatus,XmlBuildArchiveStatus>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/builds/archivestatuses/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getallbuildstatusesusingget]]
==== Get Build Statuses
....
GET /constants/builds/statuses
....


===== Description
Get all valid values for the Status field for Builds.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlbuildstatuslist,XmlBuildStatusList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/builds/statuses
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "statuses" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ]
}
----


[[_getbuildstatusbyidusingget]]
==== Get Build Status by Identifier
....
GET /constants/builds/statuses/{id}
....


===== Description
Get a single valid Status value for Builds by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlbuildstatus,XmlBuildStatus>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/builds/statuses/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getalldeploystatusesusingget]]
==== Get Deploy Statuses
....
GET /constants/deploys/statuses
....


===== Description
Get all valid values for the Status field for Deploys.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmldeploystatuslist,XmlDeployStatusList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/deploys/statuses
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "statuses" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ]
}
----


[[_getdeploystatusbyidusingget]]
==== Get Deploy Status by Identifier
....
GET /constants/deploys/statuses/{id}
....


===== Description
Get a single valid Status value for Deploys by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmldeploystatus,XmlDeployStatus>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/deploys/statuses/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getalllevelrequestactiontypesusingget]]
==== Get Level Request Action Types
....
GET /constants/levelrequests/actiontypes
....


===== Description
Get all valid values for the Action Type field for Level Requests.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmllevelrequestactiontypelist,XmlLevelRequestActionTypeList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/levelrequests/actiontypes
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "actiontypes" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ],
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ]
}
----


[[_getlevelrequestactiontypebyidusingget]]
==== Get Level Request Action Type by Identifier
....
GET /constants/levelrequests/actiontypes/{id}
....


===== Description
Get a single valid Action Type value for Level Requests by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmllevelrequestactiontype,XmlLevelRequestActionType>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/levelrequests/actiontypes/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getalllevelrequeststatusesusingget]]
==== Get Level Request Statuses
....
GET /constants/levelrequests/statuses
....


===== Description
Get all valid values for the Status field for Level Requests.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmllevelrequeststatuslist,XmlLevelRequestStatusList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/levelrequests/statuses
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "statuses" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ]
}
----


[[_getlevelrequeststatusbyidusingget]]
==== Get Level Request Status by Identifier
....
GET /constants/levelrequests/statuses/{id}
....


===== Description
Get a single valid Status value for Level Requests by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmllevelrequeststatus,XmlLevelRequestStatus>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/levelrequests/statuses/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getalllevelrequesttypesusingget]]
==== Get Level Request Types
....
GET /constants/levelrequests/types
....


===== Description
Get all valid values for the Type field for Level Requests.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmllevelrequesttypelist,XmlLevelRequestTypeList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/levelrequests/types
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "types" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ]
}
----


[[_getlevelrequesttypebyidusingget]]
==== Get Level Request Type by Identifier
....
GET /constants/levelrequests/types/{id}
....


===== Description
Get a single valid Type value for Level Requests by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmllevelrequesttype,XmlLevelRequestType>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/levelrequests/types/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getallagentstatusesusingget]]
==== Get Machine Agent Statuses
....
GET /constants/machines/agentstatuses
....


===== Description
Get all valid values for the Agent Status field for Machines.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlagentstatuslist,XmlAgentStatusList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/machines/agentstatuses
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "agentstatuses" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ],
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ]
}
----


[[_getagentstatusbyidusingget]]
==== Get Machine Agent Status by Identifier
....
GET /constants/machines/agentstatuses/{id}
....


===== Description
Get a single valid Agent Status value for Machines by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlagentstatus,XmlAgentStatus>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/machines/agentstatuses/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getalloperatingsystemsusingget]]
==== Get Machine Operating Systems
....
GET /constants/machines/operatingsystems
....


===== Description
Get all valid values for the Operating System field for Machines.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmloperatingsystemlist,XmlOperatingSystemList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/machines/operatingsystems
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "operatingsystems" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ]
}
----


[[_getoperatingsystembyidusingget]]
==== Get Machine Operating System by Identifier
....
GET /constants/machines/operatingsystems/{id}
....


===== Description
Get a single valid Operating System value for Machines by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmloperatingsystem,XmlOperatingSystem>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/machines/operatingsystems/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getallserverstatusesusingget]]
==== Get Machine Server Statuses
....
GET /constants/machines/serverstatuses
....


===== Description
Get all valid values for the Server Status field for Machines.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlserverstatuslist,XmlServerStatusList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/machines/serverstatuses
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "serverstatuses" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ]
}
----


[[_getserverstatusbyidusingget]]
==== Get Machine Server Status by Identifier
....
GET /constants/machines/serverstatuses/{id}
....


===== Description
Get a single valid Server Status value for Machines by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlserverstatus,XmlServerStatus>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/machines/serverstatuses/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getallpackagestatusesusingget]]
==== Get Package Statuses
....
GET /constants/packages/statuses
....


===== Description
Get all valid values for the Status field for Packages.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlpackagestatuslist,XmlPackageStatusList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/packages/statuses
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "statuses" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ]
}
----


[[_getpackagestatusbyidusingget]]
==== Get Package Status by Identifier
....
GET /constants/packages/statuses/{id}
....


===== Description
Get a single valid Status value for Packages by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlpackagestatus,XmlPackageStatus>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/packages/statuses/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getallphaselogformattypesusingget]]
==== Get Phase Log Format Types
....
GET /constants/phases/formattypes
....


===== Description
Get all valid values for the Format Type field for Phase Logs.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlphaselogformattypelist,XmlPhaseLogFormatTypeList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/phases/formattypes
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "formattypes" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ],
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ]
}
----


[[_getphaselogformattypebyidusingget]]
==== Get Phase Log Format Type by Identifier
....
GET /constants/phases/formattypes/{id}
....


===== Description
Get a single valid Format Type value for Phase Logs by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlphaselogformattype,XmlPhaseLogFormatType>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/phases/formattypes/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getallphaselogstatusesusingget]]
==== Get Phase Log Statuses
....
GET /constants/phases/statuses
....


===== Description
Get all valid values for the Status field for Phase Logs.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlphaselogstatuslist,XmlPhaseLogStatusList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/phases/statuses
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "statuses" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ]
}
----


[[_getphaselogstatusbyidusingget]]
==== Get Phase Log Status by Identifier
....
GET /constants/phases/statuses/{id}
....


===== Description
Get a single valid Status value for Phase Logs by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlphaselogstatus,XmlPhaseLogStatus>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/phases/statuses/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getallprojecttypesusingget]]
==== Get Project Types
....
GET /constants/projects/projecttypes
....


===== Description
Get all valid values for the Type field for Projects.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlprojecttypelist,XmlProjectTypeList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/projects/projecttypes
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "projecttypes" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ]
}
----


[[_getprojecttypebyidusingget]]
==== Get Project Type by Identifier
....
GET /constants/projects/projecttypes/{id}
....


===== Description
Get a single valid Type value for Projects by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlprojecttype,XmlProjectType>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/projects/projecttypes/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getallbuildtypesusingget]]
==== Get Project Stream Build Types
....
GET /constants/projectstreams/buildtypes
....


===== Description
Get all valid values for the Build Type field for Project Streams.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlbuildtypelist,XmlBuildTypeList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/projectstreams/buildtypes
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "buildtypes" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ],
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ]
}
----


[[_getbuildtypebyidusingget]]
==== Get Project Stream Build Types by Identifier
....
GET /constants/projectstreams/buildtypes/{id}
....


===== Description
Get a single valid Build Type value for Project Streams by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlbuildtype,XmlBuildType>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/projectstreams/buildtypes/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getallprojectstreamstatusesusingget]]
==== Get Project Stream Statuses
....
GET /constants/projectstreams/statuses
....


===== Description
Get all valid values for the Status field for Project Streams.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlprojectstreamstatuslist,XmlProjectStreamStatusList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/projectstreams/statuses
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "statuses" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ]
}
----


[[_getprojectstreamstatusbyidusingget]]
==== Get Project Stream Status by Identifier
....
GET /constants/projectstreams/statuses/{id}
....


===== Description
Get a single valid Status value for Project Streams by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlprojectstreamstatus,XmlProjectStreamStatus>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/projectstreams/statuses/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_getallrepositorylayoutsusingget]]
==== Get Subversion Repository Layouts
....
GET /constants/subversions/repository-layouts
....


===== Description
Get all valid values for the Repository Layout field for Subversion.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlrepositorylayoutlist,XmlRepositoryLayoutList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/subversions/repository-layouts
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "repository-layouts" : [ {
    "id" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "text" : "string"
  } ]
}
----


[[_getrepositorylayoutbyidusingget]]
==== Get Subversion Repository Layout by Identifier
....
GET /constants/subversions/repository-layouts/{id}
....


===== Description
Get a single valid Repository Layout value for Subversion by Identifier.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The Identifier of the constant to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlrepositorylayout,XmlRepositoryLayout>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/constants/subversions/repository-layouts/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "text" : "string"
}
----


[[_create_level_requests_resource]]
===  Create Level Requests
This resource may be used to Create a Level Request.


[[_createlevelrequestusingpost]]
==== Post a Create Level Request View to Create a Level Request
....
POST /createlevelrequest
....


===== Description
Post a Create Level Request View containing settings for a Level Request. If the settings are valid, the Level Request will be created.
 The response will contain some information about the newly created Level Request.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**xmlCLRView** +
__required__|The Create Level Request View containing the settings for creating a Level Request.|<<RESTAPI_Definitions.adoc#_xmlclrview,XmlCLRView>>
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**201**|Created|<<RESTAPI_Definitions.adoc#_xmlcreatelevelrequestview,XmlCreateLevelRequestView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/createlevelrequest
----


====== Request body
[source,json]
----
{
  "build-number" : "30",
  "deploys-to-execute" : "DeployEnv1,DeployEnv2",
  "description" : "Level Request description",
  "id" : "urn:alm:viewName:1:1",
  "level" : "LevelName",
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "package" : "PackageName",
  "parameters" : {
    "string" : "string"
  },
  "project" : "ProjectName",
  "projectstream" : "1-0",
  "redeliver" : "true",
  "start-date" : "2019-11-22T08:17:39+0000",
  "tag" : "B1-0_1"
}
----


===== Example HTTP response

====== Response 201
[source,json]
----
{
  "buildnumber" : 1,
  "description" : "The description of the created Level Request",
  "id" : "urn:alm:viewName:1:1",
  "level-id" : 1,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "package-id" : 1,
  "projectstream" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "requested-datetime" : "2019-11-22T08:17:39",
  "tag" : "B1-0_1",
  "user" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  }
}
----


[[_getemptyxmlclrviewusingget]]
==== Get Empty Create Level Request View
....
GET /createlevelrequest
....


===== Description
Get an empty Create Level Request View that can be filled in to create a new Level Request.


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlclrview,XmlCLRView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/createlevelrequest
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "build-number" : "30",
  "deploys-to-execute" : "DeployEnv1,DeployEnv2",
  "description" : "Level Request description",
  "id" : "urn:alm:viewName:1:1",
  "level" : "LevelName",
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "package" : "PackageName",
  "parameters" : {
    "string" : "string"
  },
  "project" : "ProjectName",
  "projectstream" : "1-0",
  "redeliver" : "true",
  "start-date" : "2019-11-22T08:17:39+0000",
  "tag" : "B1-0_1"
}
----


[[_deploys_resource]]
===  Deploys
This resource represents Deploys. Use it to obtain details of the existing Deploys.


[[_getlevelrequestdeployphasesbyoidusingget]]
==== Get Phases of Deploy
....
GET /deploys/{deployId}/phases
....


===== Description
Get the Phases of a specific Deploy.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**deployId** +
__required__|The identifier of the Deploy to retrieve the Phases for.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlphaselogviewlist,XmlPhaseLogViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/deploys/1/phases
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "phases" : [ {
    "display-name" : "Execute Script Phase",
    "duration" : 178890402,
    "end-datetime" : "2019-11-22T08:17:50",
    "formattingData" : "/xslt/ant/log.xsl",
    "id" : "urn:alm:viewName:1:1",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "log-format" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "message" : "Message",
    "phase-name" : "be.ikan.scm4all.phases.core.executeScript",
    "phase-version" : "5.9.0",
    "stackTrace" : "Stack trace",
    "start-datetime" : "2019-11-22T08:17:39",
    "status" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    }
  } ],
  "total" : 0
}
----


[[_git_repositories_resource]]
===  Git Repositories
This resource represents Git Repositories. Use it to obtain details of the existing Git Repositories.


[[_getallusingget]]
==== Get Git Repositories paginated
....
GET /gits
....


===== Description
Get a paginated list of Git Repositories, optionally filtered by name or userid.
 Sorting can be done by name.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**name** +
__optional__|The name to filter the Git Repositories by.|string|
|**Query**|**page** +
__optional__|The page to retrieve, defaulted to 1.|string|`"1"`
|**Query**|**pagesize** +
__optional__|The page size to retrieve, defaulted to 10.|string|`"10"`
|**Query**|**sortcolumn** +
__optional__|The attribute to sort the result by, check the endpoint description for the possible values.|string|
|**Query**|**sortdirection** +
__optional__|The sort direction to order the result, defaulted to ascending.|enum (desc, descending, true, asc, ascending, false)|`"asc"`
|**Query**|**userid** +
__optional__|The userid to filter the Git Repositories by.|string|
|**Query**|**view** +
__optional__|Whether to show only a list of Git Repository links or also all the Git Repository attributes.|enum (links, all)|
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlgitviewlist,XmlGitViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/gits
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "gits" : [ {
    "cache-location" : "file:///C:/almdemo/repository/git/",
    "clone-with-filter-blob-none" : true,
    "command-path" : "c:/vcrs/git/bin",
    "default-branch-name" : "main",
    "description" : "description",
    "id" : "urn:alm:viewName:1:1",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "name" : "GITRepository",
    "password" : "********",
    "repository-push-url" : "file:///C:/almdemo/repository/git/",
    "repository-url" : "file:///C:/almdemo/repository/git/",
    "timeout" : 30,
    "type" : "git",
    "user-id" : "gituser"
  } ],
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0
}
----


[[_getbyoidusingget]]
==== Get Git Repository
....
GET /gits/{id}
....


===== Description
Get the details of a specific Git Repository.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Git Repository to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlgitview,XmlGitView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/gits/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "cache-location" : "file:///C:/almdemo/repository/git/",
  "clone-with-filter-blob-none" : true,
  "command-path" : "c:/vcrs/git/bin",
  "default-branch-name" : "main",
  "description" : "description",
  "id" : "urn:alm:viewName:1:1",
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "name" : "GITRepository",
  "password" : "********",
  "repository-push-url" : "file:///C:/almdemo/repository/git/",
  "repository-url" : "file:///C:/almdemo/repository/git/",
  "timeout" : 30,
  "type" : "git",
  "user-id" : "gituser"
}
----


[[_getprojectsbygitoidusingget]]
==== Get Projects connected to a Git Repository.
....
GET /gits/{id}/projects
....


===== Description
Get the projects connected to a specific Git Repository.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Git Repository to retrieve the Projects for.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlprojectviewlist,XmlProjectViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/gits/1/projects
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "projects" : [ {
    "admingroup" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "archived" : true,
    "buildscript" : "build.xml",
    "deployscript" : "deploy.xml",
    "description" : "description",
    "id" : "urn:alm:viewName:1:1",
    "issuetrackingsystem" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "locked" : true,
    "name" : "name",
    "projecttype" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "usergroup" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "vcr" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "vcr-projectname" : "Customers"
  } ],
  "total" : 0
}
----


[[_issue_tracking_systems_resource]]
===  Issue Tracking Systems
This resource represents Issue Tracking Systems. Use it to obtain details of the existing Issue Tracking Systems.


[[_getallusingget_1]]
==== Get Issue Tracking Systems paginated
....
GET /issuetrackingsystems
....


===== Description
Get a paginated list of Issue Tracking Systems, optionally filtered by name, pluginfactoryclass or url.
 Sorting can be done by name.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**name** +
__optional__|The name to filter the Issue Tracking Systems by.|string|
|**Query**|**page** +
__optional__|The page to retrieve, defaulted to 1.|string|`"1"`
|**Query**|**pagesize** +
__optional__|The page size to retrieve, defaulted to 10.|string|`"10"`
|**Query**|**pluginfactoryclass** +
__optional__|The Plugin Factory Class to filter the Issue Tracking Systems by.|string|
|**Query**|**sortcolumn** +
__optional__|The attribute to sort the result by, check the endpoint description for the possible values.|string|
|**Query**|**sortdirection** +
__optional__|The sort direction to order the result, defaulted to ascending.|enum (desc, descending, true, asc, ascending, false)|`"asc"`
|**Query**|**url** +
__optional__|The URL to filter the Issue Tracking Systems by.|string|
|**Query**|**view** +
__optional__|Whether to show only a list of Issue Tracking System links or also all the Issue Tracking System attributes.|enum (links, all)|
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlissuetrackingsystemviewlist,XmlIssueTrackingSystemViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/issuetrackingsystems
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "issuetrackingsystems" : [ {
    "add-comments" : true,
    "description" : "description",
    "id" : "urn:alm:viewName:1:1",
    "issue-id-pattern" : "[0-9]+",
    "issue-pattern" : "[0-9A-Z][0-9A-Z][0-9A-Z]*-[0-9]+",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "name" : "ALM Issues System",
    "password" : "p@ssw0rd",
    "plugin-factory-class" : "string",
    "url" : "http://example.com/issues/${issueId}",
    "user" : "username"
  } ],
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0
}
----


[[_getbyoidusingget_1]]
==== Get Issue Tracking System
....
GET /issuetrackingsystems/{id}
....


===== Description
Get the details of a specific Issue Tracking System.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Issue Tracking System to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlissuetrackingsystemview,XmlIssueTrackingSystemView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/issuetrackingsystems/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "add-comments" : true,
  "description" : "description",
  "id" : "urn:alm:viewName:1:1",
  "issue-id-pattern" : "[0-9]+",
  "issue-pattern" : "[0-9A-Z][0-9A-Z][0-9A-Z]*-[0-9]+",
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "name" : "ALM Issues System",
  "password" : "p@ssw0rd",
  "plugin-factory-class" : "string",
  "url" : "http://example.com/issues/${issueId}",
  "user" : "username"
}
----


[[_getallpropertiesusingget]]
==== Get Issue Tracking Systems Properties
....
GET /issuetrackingsystems/{id}/issuetrackingsystemproperties
....


===== Description
Get a list of Issue Tracking Systems Properties for a specific Issue Tracking System.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Issue Tracking System to retrieve the properties for.|integer (int32)
|**Query**|**view** +
__optional__|Whether to show only a list of Issue Tracking System Property links or also all the Issue Tracking System Property attributes.|enum (links, all)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlissuetrackingsystemviewlist,XmlIssueTrackingSystemViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/issuetrackingsystems/1/issuetrackingsystemproperties
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "issuetrackingsystems" : [ {
    "add-comments" : true,
    "description" : "description",
    "id" : "urn:alm:viewName:1:1",
    "issue-id-pattern" : "[0-9]+",
    "issue-pattern" : "[0-9A-Z][0-9A-Z][0-9A-Z]*-[0-9]+",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "name" : "ALM Issues System",
    "password" : "p@ssw0rd",
    "plugin-factory-class" : "string",
    "url" : "http://example.com/issues/${issueId}",
    "user" : "username"
  } ],
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0
}
----


[[_getprojectsbyissuetrackingsystemsoidusingget]]
==== Get Projects connected to the Issue Tracking System
....
GET /issuetrackingsystems/{id}/projects
....


===== Description
Get a list of Projects connected to the Issue Tracking System.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Issue Tracking System to get the connected Projects for.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlprojectviewlist,XmlProjectViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/issuetrackingsystems/1/projects
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "projects" : [ {
    "admingroup" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "archived" : true,
    "buildscript" : "build.xml",
    "deployscript" : "deploy.xml",
    "description" : "description",
    "id" : "urn:alm:viewName:1:1",
    "issuetrackingsystem" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "locked" : true,
    "name" : "name",
    "projecttype" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "usergroup" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "vcr" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "vcr-projectname" : "Customers"
  } ],
  "total" : 0
}
----


[[_getpropertybyoidusingget]]
==== Get Issue Tracking System Property
....
GET /issuetrackingsystems/{issueTrackingSystemId}/issuetrackingsystemproperties/{issueTrackingSystemPropertyId}
....


===== Description
Get the details of a specific Issue Tracking System Property.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**issueTrackingSystemId** +
__required__|The identifier of the Issue Tracking System to retrieve the Property of.|integer (int32)
|**Path**|**issueTrackingSystemPropertyId** +
__required__|The identifier of the Issue Tracking System Property to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlissuetrackingsystempropertyview,XmlIssueTrackingSystemPropertyView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/issuetrackingsystems/1/issuetrackingsystemproperties/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : "urn:alm:viewName:1:1",
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "name" : "restUrl",
  "secured" : true,
  "value" : "http://api.example.com"
}
----


[[_level_requests_resource]]
===  Level Requests
This resource represents Level Requests. Use it to patch or obtain details of existing Level Requests.


[[_getallusingget_2]]
==== Get Level Requests paginated
....
GET /levelrequests
....


===== Description
Get a paginated list of Level Requests, optionally filtered by one or more of the following attributes:
* projectname;
* projectstreamprefix;
* projectstreamsuffix;
* projectstreamshowhidden;
* levelname;
* packagename;
* packageshowhidden;
* levelrequeststatus;
* levelrequestid;
* levelrequestactiontypes;
* requesteddatetimefrom;
* requesteddatetimeto;
* enddatetimefrom;
* enddatetimeto;
* resultlimit.

Sorting can be done by any of the following attributes:
* levelrequest.oid;
* project.name;
* buildnumber;
* or startdatetime.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**enddatetimefrom** +
__optional__|The earliest Date and Time the Level Request can end at.|string|
|**Query**|**enddatetimeto** +
__optional__|The latest Date and Time the Level Request can end at.|string|
|**Query**|**levelname** +
__optional__|The Level Name to filter the Level Request by.|string|
|**Query**|**levelrequestactiontypes** +
__optional__|The Action Type to filter the Level Request by. Allowed values are between 0 and 6, inclusive.
Multiple values allowed when separated by commas (not functional in the try it out input).|string|
|**Query**|**levelrequestid** +
__optional__|The Identifier to filter the Level Request by.|integer (int32)|
|**Query**|**levelrequeststatus** +
__optional__|The Status to filter the Level Request by. Allowed values are between 0 and 11, inclusive.
Multiple values allowed when separated by commas (not functional in the try it out input).|string|
|**Query**|**packagename** +
__optional__|The Package Name to filter the Level Request by.|string|
|**Query**|**packageshowhidden** +
__optional__|Whether to show Level Requests created on hidden Packages.|boolean|
|**Query**|**page** +
__optional__|The page to retrieve, defaulted to 1.|string|`"1"`
|**Query**|**pagesize** +
__optional__|The page size to retrieve, defaulted to 10.|string|`"10"`
|**Query**|**projectname** +
__optional__|The Project Name to filter the Level Request by.|string|
|**Query**|**projectstreamprefix** +
__optional__|The Project Stream Prefix to filter the Level Request by.|string|
|**Query**|**projectstreamshowhidden** +
__optional__|Whether to show Level Requests created on hidden Project Streams.|boolean|
|**Query**|**projectstreamsuffix** +
__optional__|The Project Stream Suffix to filter the Level Request by.|string|
|**Query**|**requesteddatetimefrom** +
__optional__|The earliest Date and Time the Level Request can be requested at.|string|
|**Query**|**requesteddatetimeto** +
__optional__|The latest Date and Time the Level Request can be requested at.|string|
|**Query**|**resultlimit** +
__optional__|The maximum amount of Level Requests to search for (defaulted to 1000). Can be used to speed up requests on ALM installations with a lot of Level Requests.|integer (int32)|
|**Query**|**sortcolumn** +
__optional__|The attribute to sort the result by, check the endpoint description for the possible values.|string|
|**Query**|**sortdirection** +
__optional__|The sort direction to order the result, defaulted to ascending.|enum (desc, descending, true, asc, ascending, false)|`"asc"`
|**Query**|**view** +
__optional__|Whether to show only a list of Level Request links or also all the Level Request attributes.|enum (links, all)|
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmllevelrequestresultviewlist,XmlLevelRequestResultViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/levelrequests
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "levelrequests" : [ {
    "action-type" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "build-number" : 1,
    "created-by-user" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "created-on-datetime" : "2019-11-22T08:17:39",
    "createdby-user-id" : "global",
    "description" : "Build Level Request for Example Project",
    "end-datetime" : "2019-11-22T08:17:39",
    "id" : "urn:alm:viewName:1:1",
    "level-id" : 1,
    "level-name" : "Build",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "package" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "project" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "project-name" : "Example_Project",
    "projectstream" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "projectstream-short-notation" : "Example_Project H_1-0",
    "requested-datetime" : "2019-11-22T08:17:39",
    "start-datetime" : "2019-11-22T08:17:39",
    "status" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "type" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "vcr-tag" : "H_1-0_1"
  } ],
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0
}
----


[[_getlevelrequestbyoidusingget]]
==== Get Level Request
....
GET /levelrequests/{id}
....


===== Description
Get the details of a specific Level Request.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Level Request to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmllevelrequestresultview,XmlLevelRequestResultView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/levelrequests/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "action-type" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "build-number" : 1,
  "created-by-user" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "created-on-datetime" : "2019-11-22T08:17:39",
  "createdby-user-id" : "global",
  "description" : "Build Level Request for Example Project",
  "end-datetime" : "2019-11-22T08:17:39",
  "id" : "urn:alm:viewName:1:1",
  "level-id" : 1,
  "level-name" : "Build",
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "package" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "project" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "project-name" : "Example_Project",
  "projectstream" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "projectstream-short-notation" : "Example_Project H_1-0",
  "requested-datetime" : "2019-11-22T08:17:39",
  "start-datetime" : "2019-11-22T08:17:39",
  "status" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "type" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "vcr-tag" : "H_1-0_1"
}
----


[[_patchlevelrequestusingpatch]]
==== Patch Level Request.
....
PATCH /levelrequests/{id}
....


===== Description
Update the Description or Requested Date and Time to start a not yet running Level Request, Cancel a not yet running Level Request, or Abort a running Level Request. This can be done by
 * Update: patching the Description and/or Requested Date and Time;
 * Cancel: patching the Status to 8;
 * Abort: patching the Status to 10;


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**If-Match** +
__required__|A header parameter that should contain the value of the latest ETag header of the Level Request to patch.
 The latest ETag can be retrieved by a Get Level Request action.|string
|**Path**|**id** +
__required__|The identifier of the Level Request to patch.|integer (int32)
|**Body**|**patchView** +
__required__|patchView|<<RESTAPI_Definitions.adoc#_xmllevelrequestpatchview,XmlLevelRequestPatchView>>
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmllevelrequestresultview,XmlLevelRequestResultView>>
|**204**|No Content|No Content
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|===


===== Example HTTP request

====== Request path
----
/levelrequests/1
----


====== Request header
[source,json]
----
"c3fc3a7f25d734b03e686e4d6938c49f"
----


====== Request body
[source,json]
----
{
  "description" : "Level Request description",
  "requested-datetime" : "2019-11-22T08:17:39",
  "status" : 10
}
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "action-type" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "build-number" : 1,
  "created-by-user" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "created-on-datetime" : "2019-11-22T08:17:39",
  "createdby-user-id" : "global",
  "description" : "Build Level Request for Example Project",
  "end-datetime" : "2019-11-22T08:17:39",
  "id" : "urn:alm:viewName:1:1",
  "level-id" : 1,
  "level-name" : "Build",
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "package" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "project" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "project-name" : "Example_Project",
  "projectstream" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "projectstream-short-notation" : "Example_Project H_1-0",
  "requested-datetime" : "2019-11-22T08:17:39",
  "start-datetime" : "2019-11-22T08:17:39",
  "status" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "type" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "vcr-tag" : "H_1-0_1"
}
----


[[_getlevelrequestapprovalsbyoidusingget]]
==== Get Level Request Approvals
....
GET /levelrequests/{id}/approvals
....


===== Description
Get the Approvals of a specific Level Request.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Level Request for which to retrieve the Approvals.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlapprovalviewlist,XmlApprovalViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/levelrequests/1/approvals
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "approvals" : [ {
    "approve-datetime" : "2019-11-22T08:17:39",
    "approved-by-user" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "id" : "urn:alm:viewName:1:1",
    "level-id" : "1",
    "levelrequest" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "projectstream" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "reason" : "Approved By User X",
    "sequence-number" : 1,
    "status" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "type" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "usergroup" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    }
  } ],
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0
}
----


[[_getlevelrequestbuildsbyoidusingget]]
==== Get Level Request Builds
....
GET /levelrequests/{id}/builds
....


===== Description
Get the Builds of a specific Level Request.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Level Request for which to retrieve the Builds.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlbuildviewlist,XmlBuildViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/levelrequests/1/builds
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "builds" : [ {
    "archived-status" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "build-environment-id" : 1,
    "build-environment-name" : "CONTBUILD",
    "build-number" : 1,
    "duration" : 1000,
    "end-datetime" : "2019-11-22T08:17:39",
    "file-name" : "result.zip",
    "file-size" : 178890402,
    "id" : "urn:alm:viewName:1:1",
    "is-tagged-build" : true,
    "levelrequest" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "machine-name" : "ALMServer",
    "start-datetime" : "2019-11-22T08:17:39",
    "status" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    }
  } ],
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0
}
----


[[_getlevelrequestdeploysbyoidusingget]]
==== Get Level Request Deploys
....
GET /levelrequests/{id}/deploys
....


===== Description
Get the Deploys of a specific Level Request.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Level Request for which to retrieve the Deploys.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmldeployviewlist,XmlDeployViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/levelrequests/1/deploys
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "deploys" : [ {
    "deploy-environment-id" : 1,
    "deploy-environment-name" : "ALMServer",
    "duration" : 1000,
    "end-datetime" : "2019-11-22T08:17:39",
    "id" : "urn:alm:viewName:1:1",
    "levelrequest" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "machine-name" : "ALMServer",
    "sequence-number" : 1,
    "start-datetime" : "2019-11-22T08:17:39",
    "status" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    }
  } ],
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0
}
----


[[_getlevelrequestissuesbyoidusingget]]
==== Get Level Request Issues
....
GET /levelrequests/{id}/issues
....


===== Description
Get the Issues of a specific Level Request.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Level Request for which to retrieve the Issues.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlissueviewlist,XmlIssueViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/levelrequests/1/issues
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "issues" : [ {
    "description" : "Example Issue Description",
    "id" : "urn:alm:viewName:1:1",
    "issue-id" : "Example Issue Id",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "owner" : "Example Issue Owner",
    "priority" : "Example Issue Priority",
    "status" : "Example Issue Status",
    "url" : "Example Issue Url"
  } ],
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0
}
----


[[_getlevelrequestphasesbyoidusingget]]
==== Get Level Request Phases
....
GET /levelrequests/{id}/phases
....


===== Description
Get the Phases of a specific Level Request.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Level Request for which to retrieve the Phases.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlphaselogviewlist,XmlPhaseLogViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/levelrequests/1/phases
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "phases" : [ {
    "display-name" : "Execute Script Phase",
    "duration" : 178890402,
    "end-datetime" : "2019-11-22T08:17:50",
    "formattingData" : "/xslt/ant/log.xsl",
    "id" : "urn:alm:viewName:1:1",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "log-format" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "message" : "Message",
    "phase-name" : "be.ikan.scm4all.phases.core.executeScript",
    "phase-version" : "5.9.0",
    "stackTrace" : "Stack trace",
    "start-datetime" : "2019-11-22T08:17:39",
    "status" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    }
  } ],
  "total" : 0
}
----


[[_lifecycles_resource]]
=== Lifecycles
This resource represents Lifecycles. Use it to obtain details of the existing Lifecycles.


[[_getallusingget_3]]
==== Get Lifecycles paginated
....
GET /lifecycles
....


===== Description
Get a paginated list of Lifecycles, optionally filtered by name, description, isbase, projectname or projectid.
 Sorting can be done by name.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**description** +
__optional__|The description to filter the Lifecycles by.|string|
|**Query**|**isbase** +
__optional__|Whether the Lifecycle is a base or branch Lifecycle.|enum (true, on, yes, 1, false, off, no, 0)|
|**Query**|**name** +
__optional__|The name to filter the Lifecycles by.|string|
|**Query**|**page** +
__optional__|The page to retrieve, defaulted to 1.|string|`"1"`
|**Query**|**pagesize** +
__optional__|The page size to retrieve, defaulted to 10.|string|`"10"`
|**Query**|**projectid** +
__optional__|The Project Identifier to filter the Lifecycles by.|integer (int32)|
|**Query**|**projectname** +
__optional__|The Project Name to filter the Lifecycles by.|string|
|**Query**|**sortcolumn** +
__optional__|The attribute to sort the result by, check the endpoint description for the possible values.|string|
|**Query**|**sortdirection** +
__optional__|The sort direction to order the result, defaulted to ascending.|enum (desc, descending, true, asc, ascending, false)|`"asc"`
|**Query**|**view** +
__optional__|Whether to show only a list of Lifecycles links or also all the Lifecycle attributes.|enum (links, all)|
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmllifecycleviewlist,XmlLifecycleViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/lifecycles
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "lifecycles" : [ {
    "description" : "description",
    "id" : "urn:alm:viewName:1:1",
    "is-base" : true,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "name" : "maintenancelifecycle",
    "project" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    }
  } ],
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0
}
----


[[_getbyoidusingget_2]]
==== Get Lifecycle
....
GET /lifecycles/{id}
....


===== Description
Get the details of a specific Lifecycle.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Lifecycle to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmllifecycleview,XmlLifecycleView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/lifecycles/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "description" : "description",
  "id" : "urn:alm:viewName:1:1",
  "is-base" : true,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "name" : "maintenancelifecycle",
  "project" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  }
}
----


[[_getprojectstreamsbylifecycleoidusingget]]
==== Get Project Streams connected to a Lifecycle
....
GET /lifecycles/{id}/projectstreams
....


===== Description
Get a list of Project Streams connected to a specific Lifecycle


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Lifecycle to retrieve connected Project Streams for.|integer (int32)
|**Query**|**view** +
__optional__|Whether to show only a list of Project Streams connected links connected to a Lifecycle or also all the Project Stream attributes.|enum (links, all)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlprojectstreamviewlist,XmlProjectStreamViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/lifecycles/1/projectstreams
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "projectstreams" : [ {
    "accept-forced-build" : true,
    "archived" : true,
    "buildprefix" : "string",
    "buildsuffix" : "string",
    "buildtype" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "description" : "string",
    "highest-buildnumber" : 0,
    "id" : "urn:alm:viewName:1:1",
    "is-head" : true,
    "is-tagbased" : true,
    "lifecycle" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "lifecycle-name" : "string",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "locked" : true,
    "partial-build-tag" : "string",
    "project" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "project-name" : "string",
    "projecttype" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "status" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "tag-template" : "string",
    "vcr-branch-id" : "string"
  } ],
  "total" : 0
}
----


[[_machines_resource]]
=== Machines
This resource represents Machines. Use it to obtain details of the existing Machines.


[[_getallusingget_4]]
==== Get Machines paginated
....
GET /machines
....


===== Description
Get a paginated list of Machines, optionally filtered by name, operatingsystem, transporterprotocolid or transporterprotocolname.
 Sorting can be done by name.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**name** +
__optional__|The name to filter the Machines by.|string|
|**Query**|**operatingsystem** +
__optional__|The Operating System to filter the Machines by (0=Windows; 1=Unix; 2=Linux; 3=z/OS).|enum (0, 1, 2, 3)|
|**Query**|**page** +
__optional__|The page to retrieve, defaulted to 1.|string|`"1"`
|**Query**|**pagesize** +
__optional__|The page size to retrieve, defaulted to 10.|string|`"10"`
|**Query**|**sortcolumn** +
__optional__|The attribute to sort the result by, check the endpoint description for the possible values.|string|
|**Query**|**sortdirection** +
__optional__|The sort direction to order the result, defaulted to ascending.|enum (desc, descending, true, asc, ascending, false)|`"asc"`
|**Query**|**transporterprotocolid** +
__optional__|The Transporter Protocol ID to filter the Machines by.|integer (int32)|
|**Query**|**transporterprotocolname** +
__optional__|The Transporter Protocol Name to filter the Machines by.|string|
|**Query**|**view** +
__optional__|Whether to show only a list of Machine links or also all the Machine attributes.|enum (links, all)|
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlmachineviewlist,XmlMachineViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/machines
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "machines" : [ {
    "agent-port" : 20020,
    "description" : "description",
    "dhcp-enabled" : true,
    "dhcp-name" : "almserver.example.com",
    "id" : "urn:alm:viewName:1:1",
    "ip-address" : "127.0.0.1",
    "job-limit" : 0,
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "locked" : true,
    "name" : "ALMServer",
    "operatingsystem" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "server-port" : 20021,
    "transporterprotocol-id" : 1,
    "transporterprotocol-name" : "Local FileCopy"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0
}
----


[[_getbyoidusingget_3]]
==== Get Machine
....
GET /machines/{id}
....


===== Description
Get the details of a specific Machine.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Machine to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlmachineview,XmlMachineView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/machines/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "agent-port" : 20020,
  "description" : "description",
  "dhcp-enabled" : true,
  "dhcp-name" : "almserver.example.com",
  "id" : "urn:alm:viewName:1:1",
  "ip-address" : "127.0.0.1",
  "job-limit" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "locked" : true,
  "name" : "ALMServer",
  "operatingsystem" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "server-port" : 20021,
  "transporterprotocol-id" : 1,
  "transporterprotocol-name" : "Local FileCopy"
}
----


[[_getmachineagentlogusingget]]
==== Get Machine Agent Log
....
GET /machines/{id}/agentlog
....


===== Description
Retrieve the Agent Log of a specific Machine.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Machine to retrieve the Agent log.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlmachinestatusview,XmlMachineStatusView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/machines/1/agentlog
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "agent-log" : "string",
  "agentstatus" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "dhcp-enabled" : true,
  "dhcp-name" : "string",
  "id" : "urn:alm:viewName:1:1",
  "ip-address" : "127.0.0.1",
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "name" : "ALMServer",
  "serverstatus" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  }
}
----


[[_getmachinestatususingget]]
==== Get Machine Status
....
GET /machines/{id}/status
....


===== Description
Verify the Status of a specific Machine.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Machine to verify the status.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlmachinestatusview,XmlMachineStatusView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/machines/1/status
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "agent-log" : "string",
  "agentstatus" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "dhcp-enabled" : true,
  "dhcp-name" : "string",
  "id" : "urn:alm:viewName:1:1",
  "ip-address" : "127.0.0.1",
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "name" : "ALMServer",
  "serverstatus" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  }
}
----


[[_packages_resource]]
=== Packages
This resource represents Packages. Use it to create, update or obtain details of Packages.


[[_createpackageusingpost]]
==== Create Package
....
POST /packages
....


===== Description
Create a new Package.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**xmlCreatePackageView** +
__required__|The details of the Package to create.|<<RESTAPI_Definitions.adoc#_xmlcrupackageview,XmlCRUPackageView>>
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlcrupackageresultview,XmlCRUPackageResultView>>
|**201**|Created|No Content
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/packages
----


====== Request body
[source,json]
----
{
  "archived" : false,
  "description" : "Description for the new package",
  "filerevisions" : [ {
    "action" : "create",
    "name" : "readme.txt",
    "path" : "/demo/",
    "revision" : "1"
  } ],
  "name" : "example_package",
  "owner" : 1,
  "project" : "package_project",
  "projectstream" : "1-0",
  "status" : 0,
  "target-release-date" : "2060-10-31"
}
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : "urn:alm:viewName:1:1",
  "package" : {
    "archived" : false,
    "description" : "Description for the package",
    "id" : "urn:alm:viewName:1:1",
    "latest-levelrequest" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "name" : "example_package",
    "owner" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "project" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "project-name" : "H_1-0",
    "projectstream" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "projectstream-short-notation" : "H_1-0",
    "status" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "target-release-date" : "2030-11-22"
  },
  "packagecru-report" : [ "string" ],
  "validation-errors" : {
    "string" : "string"
  }
}
----


[[_getallusingget_5]]
==== Get Packages paginated
....
GET /packages
....


===== Description
Get a paginated list of Packages, optionally filtered by name, projectname, packageshowhidden, projectstreamshowhidden or description.
 Sorting can be done by name and description.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**description** +
__optional__|The Description to filter the Package by.|string|
|**Query**|**name** +
__optional__|The Name to filter the Packages by.|string|
|**Query**|**packageshowhidden** +
__optional__|Whether to show hidden Packages or not (defaults to false).|boolean|
|**Query**|**page** +
__optional__|The page to retrieve, defaulted to 1.|string|`"1"`
|**Query**|**pagesize** +
__optional__|The page size to retrieve, defaulted to 10.|string|`"10"`
|**Query**|**projectname** +
__optional__|The Project Name to filter the Packages by.|string|
|**Query**|**projectstreamshowhidden** +
__optional__|Whether to show Packages for hidden Project Streams (defaults to false).|boolean|
|**Query**|**sortcolumn** +
__optional__|The attribute to sort the result by, check the endpoint description for the possible values.|string|
|**Query**|**sortdirection** +
__optional__|The sort direction to order the result, defaulted to ascending.|enum (desc, descending, true, asc, ascending, false)|`"asc"`
|**Query**|**view** +
__optional__|Whether to show only a list of Package links or also all the Package attributes.|enum (links, all)|
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlpackageviewlist,XmlPackageViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/packages
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "packages" : [ {
    "archived" : false,
    "description" : "Description for the package",
    "id" : "urn:alm:viewName:1:1",
    "latest-levelrequest" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "name" : "example_package",
    "owner" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "project" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "project-name" : "H_1-0",
    "projectstream" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "projectstream-short-notation" : "H_1-0",
    "status" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "target-release-date" : "2030-11-22"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0
}
----


[[_getbyoidusingget_4]]
==== Get Package
....
GET /packages/{id}
....


===== Description
Get the details of a specific Package.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Package to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlpackageview,XmlPackageView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/packages/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "archived" : false,
  "description" : "Description for the package",
  "id" : "urn:alm:viewName:1:1",
  "latest-levelrequest" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "name" : "example_package",
  "owner" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "project" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "project-name" : "H_1-0",
  "projectstream" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "projectstream-short-notation" : "H_1-0",
  "status" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "target-release-date" : "2030-11-22"
}
----


[[_updatepackageusingpatch]]
==== Update Package
....
PATCH /packages/{id}
....


===== Description
Update an existing Package and/or the File Revisions of the Package.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Header**|**If-Match** +
__required__|A header parameter that should contain the value of the latest ETag header of the Package to update.
 The latest ETag can be retrieved by a Get Package action.|string
|**Header**|**If-Match-Contents** +
__required__|A header parameter that should contain the value of the latest ETag header of the Package File Revisions to update.
 The latest ETag can be retrieved by a Get File Revisions action.|string
|**Path**|**id** +
__required__|The identifier of the Package to update.|integer (int32)
|**Body**|**xmlCRUPackageView** +
__required__|The updated details and/or file revisions of the Package.|<<RESTAPI_Definitions.adoc#_xmlcrupackageview,XmlCRUPackageView>>
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlcrupackageresultview,XmlCRUPackageResultView>>
|**204**|No Content|No Content
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|===


===== Example HTTP request

====== Request path
----
/packages/1
----


====== Request header
[source,json]
----
"c3fc3a7f25d734b03e686e4d6938c49f"
----


====== Request body
[source,json]
----
{
  "archived" : false,
  "description" : "Description for the new package",
  "filerevisions" : [ {
    "action" : "create",
    "name" : "readme.txt",
    "path" : "/demo/",
    "revision" : "1"
  } ],
  "name" : "example_package",
  "owner" : 1,
  "project" : "package_project",
  "projectstream" : "1-0",
  "status" : 0,
  "target-release-date" : "2060-10-31"
}
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "id" : "urn:alm:viewName:1:1",
  "package" : {
    "archived" : false,
    "description" : "Description for the package",
    "id" : "urn:alm:viewName:1:1",
    "latest-levelrequest" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "name" : "example_package",
    "owner" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "project" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "project-name" : "H_1-0",
    "projectstream" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "projectstream-short-notation" : "H_1-0",
    "status" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "target-release-date" : "2030-11-22"
  },
  "packagecru-report" : [ "string" ],
  "validation-errors" : {
    "string" : "string"
  }
}
----


[[_getpackagefilerevisionsbyoidusingget]]
==== Get Package File Revisions
....
GET /packages/{id}/filerevisions
....


===== Description
Get the File Revisions linked to a specific Package.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Package for which to retrieve the File Revisions.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlfilerevisionviewlist,XmlFileRevisionViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/packages/1/filerevisions
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "filerevisions" : [ {
    "name" : "readme.txt",
    "path" : "/demo/",
    "revision" : "1"
  } ],
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0
}
----


[[_projects_resource]]
=== Projects
This resource represents Projects. Use it to obtain details of the existing Projects.


[[_getallprojectsusingget]]
==== Get Projects paginated
....
GET /projects
....


===== Description
Get a paginated list of Projects, optionally filtered by name, projecttype or locked value.
 Sorting can be done by name.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**locked** +
__optional__|Whether the Project is Locked or not.|enum (true, on, yes, 1, false, off, no, 0)|
|**Query**|**name** +
__optional__|The name to filter the Projects by.|string|
|**Query**|**page** +
__optional__|The page to retrieve, defaulted to 1.|string|`"1"`
|**Query**|**pagesize** +
__optional__|The page size to retrieve, defaulted to 10.|string|`"10"`
|**Query**|**projecttype** +
__optional__|The Project Type to filter the Projects by (0=Release-based, 1=Package-based).|enum (0, 1)|
|**Query**|**sortcolumn** +
__optional__|The attribute to sort the result by, check the endpoint description for the possible values.|string|
|**Query**|**sortdirection** +
__optional__|The sort direction to order the result, defaulted to ascending.|enum (desc, descending, true, asc, ascending, false)|`"asc"`
|**Query**|**view** +
__optional__|Whether to show only a list of Project links or also all the Project attributes.|enum (links, all)|
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlprojectviewlist,XmlProjectViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/projects
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "projects" : [ {
    "admingroup" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "archived" : true,
    "buildscript" : "build.xml",
    "deployscript" : "deploy.xml",
    "description" : "description",
    "id" : "urn:alm:viewName:1:1",
    "issuetrackingsystem" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "locked" : true,
    "name" : "name",
    "projecttype" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "usergroup" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "vcr" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "vcr-projectname" : "Customers"
  } ],
  "total" : 0
}
----


[[_getprojectbyoidusingget]]
==== Get Project
....
GET /projects/{id}
....


===== Description
Get the details of a specific Project.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Project to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlprojectview,XmlProjectView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/projects/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "admingroup" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "archived" : true,
  "buildscript" : "build.xml",
  "deployscript" : "deploy.xml",
  "description" : "description",
  "id" : "urn:alm:viewName:1:1",
  "issuetrackingsystem" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "locked" : true,
  "name" : "name",
  "projecttype" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "usergroup" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "vcr" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "vcr-projectname" : "Customers"
}
----


[[_project_export_resource]]
=== Project Export
This resource enables to export the data of an existing Project.


[[_exportprojectusingget]]
==== Export the full project structure with sub entities and references to global objects
....
GET /projectexport/{name}
....


===== Description
Export the complete project tree as a JSON or XML structure. It will contain all major/minor elements (Project Streams/Phase Parameters, ) and references to global objects (Build Tools,) so that it can be used as input to import and create a new Project.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**name** +
__required__|The Name of the Project to export.|string
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlprojectexportview,XmlProjectExportView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/projectexport/Customers
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "globalreferences" : [ {
    "attributes" : {
      "string" : "string"
    },
    "refid" : 1,
    "type" : "vcr"
  } ],
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "projecttree" : {
    "levels" : [ {
      "buildenvironments" : [ {
        "build-script" : "string",
        "build-suffix" : "string",
        "buildenvironmentparameters" : [ {
          "description" : "string",
          "dynamic" : true,
          "editable" : true,
          "id" : "urn:alm:viewName:1:1",
          "key" : "string",
          "links" : [ {
            "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
            "rel" : "LinkRel",
            "title" : "Title"
          } ],
          "mandatory" : true,
          "oid" : 0,
          "secured" : true,
          "user-controlled" : true,
          "value" : "string"
        } ],
        "buildtoolref" : "string",
        "debug" : true,
        "downloadable-build" : true,
        "id" : "urn:alm:viewName:1:1",
        "level-oid" : 0,
        "links" : [ {
          "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
          "rel" : "LinkRel",
          "title" : "Title"
        } ],
        "machineref" : "string",
        "name" : "string",
        "oid" : 0,
        "phases" : [ {
          "description" : "string",
          "environment-oid" : 0,
          "environment-type" : 0,
          "fail-on-error" : true,
          "firstphase" : true,
          "globalphase" : "string",
          "id" : "urn:alm:viewName:1:1",
          "links" : [ {
            "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
            "rel" : "LinkRel",
            "title" : "Title"
          } ],
          "next-phase-on-fail-oid" : 0,
          "next-phase-on-success-oid" : 0,
          "next-phase-on-warning-oid" : 0,
          "oid" : 0,
          "parameters" : [ {
            "globalphaseparameter" : "string",
            "id" : "urn:alm:viewName:1:1",
            "integrationref" : "string",
            "integrationtype" : 0,
            "links" : [ {
              "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
              "rel" : "LinkRel",
              "title" : "Title"
            } ],
            "name" : "string",
            "oid" : 0,
            "value" : "string"
          } ],
          "phase-name" : "string",
          "phase-version" : "string"
        } ],
        "source-location" : "string",
        "target-location" : "string",
        "user-parameters" : true
      } ],
      "debug" : true,
      "deployenvironments" : [ {
        "build-environment-oid" : 0,
        "debug" : true,
        "deploy-script" : "string",
        "deployenvironmentparameters" : [ {
          "description" : "string",
          "dynamic" : true,
          "editable" : true,
          "id" : "urn:alm:viewName:1:1",
          "key" : "string",
          "links" : [ {
            "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
            "rel" : "LinkRel",
            "title" : "Title"
          } ],
          "mandatory" : true,
          "oid" : 0,
          "secured" : true,
          "user-controlled" : true,
          "value" : "string"
        } ],
        "deploytoolref" : "string",
        "id" : "urn:alm:viewName:1:1",
        "level-oid" : 0,
        "links" : [ {
          "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
          "rel" : "LinkRel",
          "title" : "Title"
        } ],
        "machineref" : "string",
        "name" : "string",
        "oid" : 0,
        "partial-deploy" : true,
        "phases" : [ {
          "description" : "string",
          "environment-oid" : 0,
          "environment-type" : 0,
          "fail-on-error" : true,
          "firstphase" : true,
          "globalphase" : "string",
          "id" : "urn:alm:viewName:1:1",
          "links" : [ {
            "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
            "rel" : "LinkRel",
            "title" : "Title"
          } ],
          "next-phase-on-fail-oid" : 0,
          "next-phase-on-success-oid" : 0,
          "next-phase-on-warning-oid" : 0,
          "oid" : 0,
          "parameters" : [ {
            "globalphaseparameter" : "string",
            "id" : "urn:alm:viewName:1:1",
            "integrationref" : "string",
            "integrationtype" : 0,
            "links" : [ {
              "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
              "rel" : "LinkRel",
              "title" : "Title"
            } ],
            "name" : "string",
            "oid" : 0,
            "value" : "string"
          } ],
          "phase-name" : "string",
          "phase-version" : "string"
        } ],
        "sequence-number" : 0,
        "source-location" : "string",
        "target-location" : "string",
        "user-parameters" : true
      } ],
      "description" : "string",
      "id" : "urn:alm:viewName:1:1",
      "links" : [ {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      } ],
      "locked" : true,
      "name" : "string",
      "notification-criteria" : 0,
      "notification-type" : 0,
      "oid" : 0,
      "phases" : [ {
        "description" : "string",
        "environment-oid" : 0,
        "environment-type" : 0,
        "fail-on-error" : true,
        "firstphase" : true,
        "globalphase" : "string",
        "id" : "urn:alm:viewName:1:1",
        "links" : [ {
          "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
          "rel" : "LinkRel",
          "title" : "Title"
        } ],
        "next-phase-on-fail-oid" : 0,
        "next-phase-on-success-oid" : 0,
        "next-phase-on-warning-oid" : 0,
        "oid" : 0,
        "parameters" : [ {
          "globalphaseparameter" : "string",
          "id" : "urn:alm:viewName:1:1",
          "integrationref" : "string",
          "integrationtype" : 0,
          "links" : [ {
            "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
            "rel" : "LinkRel",
            "title" : "Title"
          } ],
          "name" : "string",
          "oid" : 0,
          "value" : "string"
        } ],
        "phase-name" : "string",
        "phase-version" : "string"
      } ],
      "post-notification-criteria" : 0,
      "postapprovals" : [ {
        "controlled-by-usergroup" : "string",
        "id" : "urn:alm:viewName:1:1",
        "level-oid" : 0,
        "links" : [ {
          "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
          "rel" : "LinkRel",
          "title" : "Title"
        } ],
        "oid" : 0,
        "sequencenumber" : 0
      } ],
      "postnotification-usergroupref" : "string",
      "preapprovals" : [ {
        "controlled-by-usergroup" : "string",
        "id" : "urn:alm:viewName:1:1",
        "levelOid" : 0,
        "links" : [ {
          "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
          "rel" : "LinkRel",
          "title" : "Title"
        } ],
        "oid" : 0,
        "sequencenumber" : 0
      } ],
      "prenotification-usergroupref" : "string",
      "requester-usergroupref" : "string",
      "scheduleref" : "string",
      "type" : 0
    } ],
    "lifecycles" : [ {
      "description" : "string",
      "id" : "urn:alm:viewName:1:1",
      "is-base" : true,
      "lifecycle-associations" : [ {
        "id" : "urn:alm:viewName:1:1",
        "level-oid" : 0,
        "lifecycle-oid" : 0,
        "links" : [ {
          "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
          "rel" : "LinkRel",
          "title" : "Title"
        } ],
        "oid" : 0,
        "optional" : true,
        "optional-deploy" : true,
        "sequence-number" : 0
      } ],
      "links" : [ {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      } ],
      "name" : "string",
      "oid" : 0
    } ],
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "project" : {
      "admingroupref" : "string",
      "archived" : true,
      "buildscript" : "string",
      "deployscript" : "string",
      "description" : "string",
      "id" : "urn:alm:viewName:1:1",
      "issuetrackingsystemref" : "string",
      "links" : [ {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      } ],
      "locked" : true,
      "name" : "string",
      "oid" : 0,
      "projecttype" : 0,
      "usergroupref" : "string",
      "vcr-projectname" : "string",
      "vcrref" : "string"
    },
    "projectstreams" : [ {
      "accept-forced-build" : true,
      "archived" : true,
      "buildprefix" : "string",
      "buildsuffix" : "string",
      "buildtype" : 0,
      "description" : "string",
      "highest-buildnumber" : 0,
      "id" : "urn:alm:viewName:1:1",
      "is-head" : true,
      "is-tagbased" : true,
      "lifecycle-oid" : 0,
      "links" : [ {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      } ],
      "locked" : true,
      "oid" : 0,
      "partial-build-tag" : "string",
      "status" : 0,
      "tag-template" : "string",
      "vcr-branch-id" : "string"
    } ]
  },
  "version" : "5-9.0"
}
----


[[_project_import_resource]]
=== Project Import
This resource enables to import a complete new Project.


[[_importprojectusingpost]]
==== Import and create a complete project structure with sub entities and references to global objects
....
POST /projectimport
....


===== Description
Import the project tree that is submitted as a JSON or XML structure. The Project can be created with all its major and minor elements (from Project Streams to Phase Parameters) and set links to existing global references (like Build Tools, VCRs, ) so that a full functional Project is obtained.
 The input can be tested without a real import by using the dry-run parameter.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Query**|**dry-run** +
__optional__|Whether to just validate the submitted project tree and global references without actually importing the project.|enum (true, on, yes, 1, false, off, no, 0)
|**Body**|**exportView** +
__required__|exportView|<<RESTAPI_Definitions.adoc#_xmlprojectexportview,XmlProjectExportView>>
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlvalidatedprojectimportview,XmlValidatedProjectImportView>>
|**201**|Created|No Content
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/projectimport
----


====== Request body
[source,json]
----
{
  "globalreferences" : [ {
    "attributes" : {
      "string" : "string"
    },
    "refid" : 1,
    "type" : "vcr"
  } ],
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "projecttree" : {
    "levels" : [ {
      "buildenvironments" : [ {
        "build-script" : "string",
        "build-suffix" : "string",
        "buildenvironmentparameters" : [ {
          "description" : "string",
          "dynamic" : true,
          "editable" : true,
          "id" : "urn:alm:viewName:1:1",
          "key" : "string",
          "links" : [ {
            "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
            "rel" : "LinkRel",
            "title" : "Title"
          } ],
          "mandatory" : true,
          "oid" : 0,
          "secured" : true,
          "user-controlled" : true,
          "value" : "string"
        } ],
        "buildtoolref" : "string",
        "debug" : true,
        "downloadable-build" : true,
        "id" : "urn:alm:viewName:1:1",
        "level-oid" : 0,
        "links" : [ {
          "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
          "rel" : "LinkRel",
          "title" : "Title"
        } ],
        "machineref" : "string",
        "name" : "string",
        "oid" : 0,
        "phases" : [ {
          "description" : "string",
          "environment-oid" : 0,
          "environment-type" : 0,
          "fail-on-error" : true,
          "firstphase" : true,
          "globalphase" : "string",
          "id" : "urn:alm:viewName:1:1",
          "links" : [ {
            "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
            "rel" : "LinkRel",
            "title" : "Title"
          } ],
          "next-phase-on-fail-oid" : 0,
          "next-phase-on-success-oid" : 0,
          "next-phase-on-warning-oid" : 0,
          "oid" : 0,
          "parameters" : [ {
            "globalphaseparameter" : "string",
            "id" : "urn:alm:viewName:1:1",
            "integrationref" : "string",
            "integrationtype" : 0,
            "links" : [ {
              "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
              "rel" : "LinkRel",
              "title" : "Title"
            } ],
            "name" : "string",
            "oid" : 0,
            "value" : "string"
          } ],
          "phase-name" : "string",
          "phase-version" : "string"
        } ],
        "source-location" : "string",
        "target-location" : "string",
        "user-parameters" : true
      } ],
      "debug" : true,
      "deployenvironments" : [ {
        "build-environment-oid" : 0,
        "debug" : true,
        "deploy-script" : "string",
        "deployenvironmentparameters" : [ {
          "description" : "string",
          "dynamic" : true,
          "editable" : true,
          "id" : "urn:alm:viewName:1:1",
          "key" : "string",
          "links" : [ {
            "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
            "rel" : "LinkRel",
            "title" : "Title"
          } ],
          "mandatory" : true,
          "oid" : 0,
          "secured" : true,
          "user-controlled" : true,
          "value" : "string"
        } ],
        "deploytoolref" : "string",
        "id" : "urn:alm:viewName:1:1",
        "level-oid" : 0,
        "links" : [ {
          "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
          "rel" : "LinkRel",
          "title" : "Title"
        } ],
        "machineref" : "string",
        "name" : "string",
        "oid" : 0,
        "partial-deploy" : true,
        "phases" : [ {
          "description" : "string",
          "environment-oid" : 0,
          "environment-type" : 0,
          "fail-on-error" : true,
          "firstphase" : true,
          "globalphase" : "string",
          "id" : "urn:alm:viewName:1:1",
          "links" : [ {
            "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
            "rel" : "LinkRel",
            "title" : "Title"
          } ],
          "next-phase-on-fail-oid" : 0,
          "next-phase-on-success-oid" : 0,
          "next-phase-on-warning-oid" : 0,
          "oid" : 0,
          "parameters" : [ {
            "globalphaseparameter" : "string",
            "id" : "urn:alm:viewName:1:1",
            "integrationref" : "string",
            "integrationtype" : 0,
            "links" : [ {
              "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
              "rel" : "LinkRel",
              "title" : "Title"
            } ],
            "name" : "string",
            "oid" : 0,
            "value" : "string"
          } ],
          "phase-name" : "string",
          "phase-version" : "string"
        } ],
        "sequence-number" : 0,
        "source-location" : "string",
        "target-location" : "string",
        "user-parameters" : true
      } ],
      "description" : "string",
      "id" : "urn:alm:viewName:1:1",
      "links" : [ {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      } ],
      "locked" : true,
      "name" : "string",
      "notification-criteria" : 0,
      "notification-type" : 0,
      "oid" : 0,
      "phases" : [ {
        "description" : "string",
        "environment-oid" : 0,
        "environment-type" : 0,
        "fail-on-error" : true,
        "firstphase" : true,
        "globalphase" : "string",
        "id" : "urn:alm:viewName:1:1",
        "links" : [ {
          "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
          "rel" : "LinkRel",
          "title" : "Title"
        } ],
        "next-phase-on-fail-oid" : 0,
        "next-phase-on-success-oid" : 0,
        "next-phase-on-warning-oid" : 0,
        "oid" : 0,
        "parameters" : [ {
          "globalphaseparameter" : "string",
          "id" : "urn:alm:viewName:1:1",
          "integrationref" : "string",
          "integrationtype" : 0,
          "links" : [ {
            "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
            "rel" : "LinkRel",
            "title" : "Title"
          } ],
          "name" : "string",
          "oid" : 0,
          "value" : "string"
        } ],
        "phase-name" : "string",
        "phase-version" : "string"
      } ],
      "post-notification-criteria" : 0,
      "postapprovals" : [ {
        "controlled-by-usergroup" : "string",
        "id" : "urn:alm:viewName:1:1",
        "level-oid" : 0,
        "links" : [ {
          "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
          "rel" : "LinkRel",
          "title" : "Title"
        } ],
        "oid" : 0,
        "sequencenumber" : 0
      } ],
      "postnotification-usergroupref" : "string",
      "preapprovals" : [ {
        "controlled-by-usergroup" : "string",
        "id" : "urn:alm:viewName:1:1",
        "levelOid" : 0,
        "links" : [ {
          "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
          "rel" : "LinkRel",
          "title" : "Title"
        } ],
        "oid" : 0,
        "sequencenumber" : 0
      } ],
      "prenotification-usergroupref" : "string",
      "requester-usergroupref" : "string",
      "scheduleref" : "string",
      "type" : 0
    } ],
    "lifecycles" : [ {
      "description" : "string",
      "id" : "urn:alm:viewName:1:1",
      "is-base" : true,
      "lifecycle-associations" : [ {
        "id" : "urn:alm:viewName:1:1",
        "level-oid" : 0,
        "lifecycle-oid" : 0,
        "links" : [ {
          "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
          "rel" : "LinkRel",
          "title" : "Title"
        } ],
        "oid" : 0,
        "optional" : true,
        "optional-deploy" : true,
        "sequence-number" : 0
      } ],
      "links" : [ {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      } ],
      "name" : "string",
      "oid" : 0
    } ],
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "project" : {
      "admingroupref" : "string",
      "archived" : true,
      "buildscript" : "string",
      "deployscript" : "string",
      "description" : "string",
      "id" : "urn:alm:viewName:1:1",
      "issuetrackingsystemref" : "string",
      "links" : [ {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      } ],
      "locked" : true,
      "name" : "string",
      "oid" : 0,
      "projecttype" : 0,
      "usergroupref" : "string",
      "vcr-projectname" : "string",
      "vcrref" : "string"
    },
    "projectstreams" : [ {
      "accept-forced-build" : true,
      "archived" : true,
      "buildprefix" : "string",
      "buildsuffix" : "string",
      "buildtype" : 0,
      "description" : "string",
      "highest-buildnumber" : 0,
      "id" : "urn:alm:viewName:1:1",
      "is-head" : true,
      "is-tagbased" : true,
      "lifecycle-oid" : 0,
      "links" : [ {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      } ],
      "locked" : true,
      "oid" : 0,
      "partial-build-tag" : "string",
      "status" : 0,
      "tag-template" : "string",
      "vcr-branch-id" : "string"
    } ]
  },
  "version" : "5-9.0"
}
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "imported-project" : {
    "admingroupref" : "string",
    "archived" : true,
    "buildscript" : "string",
    "deployscript" : "string",
    "description" : "string",
    "id" : "urn:alm:viewName:1:1",
    "issuetrackingsystemref" : "string",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "locked" : true,
    "name" : "string",
    "oid" : 0,
    "projecttype" : 0,
    "usergroupref" : "string",
    "vcr-projectname" : "string",
    "vcrref" : "string"
  },
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "validation-errors" : {
    "string" : "string"
  },
  "validation-report" : [ "string" ]
}
----


[[_project_streams_resource]]
=== Project Streams
This resource represents Project Streams. Use it to obtain details of the existing Project Streams.


[[_createprojectstreamusingpost]]
==== Create Project Stream
....
POST /projectstreams
....


===== Description
Creates a Project Stream.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**xmlCreateProjectStreamView** +
__required__|The Projectstream to create.|<<RESTAPI_Definitions.adoc#_xmlcruprojectstreamview,XmlCRUProjectStreamView>>
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlprojectstreamview,XmlProjectStreamView>>
|**201**|Created|No Content
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/projectstreams
----


====== Request body
[source,json]
----
{
  "accept-forced-build" : true,
  "archived" : false,
  "buildprefix" : "1-0",
  "buildsuffix" : "1-1",
  "buildtype" : 1,
  "description" : "description",
  "highest-buildnumber" : 0,
  "is-head" : false,
  "is-tagbased" : false,
  "lifecycle-oid" : 1,
  "locked" : false,
  "project-oid" : 1,
  "status" : 1,
  "tag-template" : "${streamType}_${prefix}_${suffix}_b${buildNumber}",
  "vcr-branch-id" : "COMMON/branches/JDK11"
}
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "accept-forced-build" : true,
  "archived" : true,
  "buildprefix" : "string",
  "buildsuffix" : "string",
  "buildtype" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "description" : "string",
  "highest-buildnumber" : 0,
  "id" : "urn:alm:viewName:1:1",
  "is-head" : true,
  "is-tagbased" : true,
  "lifecycle" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "lifecycle-name" : "string",
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "locked" : true,
  "partial-build-tag" : "string",
  "project" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "project-name" : "string",
  "projecttype" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "status" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "tag-template" : "string",
  "vcr-branch-id" : "string"
}
----


[[_getallusingget_6]]
==== Get Project Streams paginated
....
GET /projectstreams
....


===== Description
Get a paginated list of Project Streams, optionally filtered by prefix, suffix, vcrbranchid, projectid, projectname or ishead value.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**ishead** +
__optional__|Whether the Project is a Head or Branch stream.|enum (true, on, yes, 1, false, off, no, 0)|
|**Query**|**page** +
__optional__|The page to retrieve, defaulted to 1.|string|`"1"`
|**Query**|**pagesize** +
__optional__|The page size to retrieve, defaulted to 10.|string|`"10"`
|**Query**|**prefix** +
__optional__|The Prefix to filter the Project Streams by.|string|
|**Query**|**projectid** +
__optional__|The Project identifier to filter the Project Streams by.|integer (int32)|
|**Query**|**projectname** +
__optional__|The Project Name to filter the Project Streams by.|string|
|**Query**|**suffix** +
__optional__|The Suffix to filter the Project Streams by.|string|
|**Query**|**vcrbranchid** +
__optional__|The VCR Branch ID to filter the Project Streams by.|string|
|**Query**|**view** +
__optional__|Whether to show only a list of Project Stream links or also all the Project Stream attributes.|enum (links, all)|
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlprojectstreamviewlist,XmlProjectStreamViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/projectstreams
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "projectstreams" : [ {
    "accept-forced-build" : true,
    "archived" : true,
    "buildprefix" : "string",
    "buildsuffix" : "string",
    "buildtype" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "description" : "string",
    "highest-buildnumber" : 0,
    "id" : "urn:alm:viewName:1:1",
    "is-head" : true,
    "is-tagbased" : true,
    "lifecycle" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "lifecycle-name" : "string",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "locked" : true,
    "partial-build-tag" : "string",
    "project" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "project-name" : "string",
    "projecttype" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "status" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "tag-template" : "string",
    "vcr-branch-id" : "string"
  } ],
  "total" : 0
}
----


[[_getbyoidusingget_5]]
==== Get Project Stream
....
GET /projectstreams/{id}
....


===== Description
Get the details of a specific Project Stream.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Project Stream to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlprojectstreamview,XmlProjectStreamView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/projectstreams/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "accept-forced-build" : true,
  "archived" : true,
  "buildprefix" : "string",
  "buildsuffix" : "string",
  "buildtype" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "description" : "string",
  "highest-buildnumber" : 0,
  "id" : "urn:alm:viewName:1:1",
  "is-head" : true,
  "is-tagbased" : true,
  "lifecycle" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "lifecycle-name" : "string",
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "locked" : true,
  "partial-build-tag" : "string",
  "project" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Other Resource"
  },
  "project-name" : "string",
  "projecttype" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "status" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "tag-template" : "string",
  "vcr-branch-id" : "string"
}
----


[[_subversion_repositories_resource]]
=== Subversion Repositories
This resource represents Subversion Repositories. Use it to obtain details of the existing Subversion Repositories.


[[_getallusingget_7]]
==== Get Subversion Repositories paginated
....
GET /subversions
....


===== Description
Get a paginated list of Subversion Repositories, optionally filtered by name or userid.
 Sorting can be done by name.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**name** +
__optional__|The name to filter the Subversion Repositories by.|string|
|**Query**|**page** +
__optional__|The page to retrieve, defaulted to 1.|string|`"1"`
|**Query**|**pagesize** +
__optional__|The page size to retrieve, defaulted to 10.|string|`"10"`
|**Query**|**sortcolumn** +
__optional__|The attribute to sort the result by, check the endpoint description for the possible values.|string|
|**Query**|**sortdirection** +
__optional__|The sort direction to order the result, defaulted to ascending.|enum (desc, descending, true, asc, ascending, false)|`"asc"`
|**Query**|**userid** +
__optional__|The userid to filter the Subversion Repositories by.|string|
|**Query**|**view** +
__optional__|Whether to show only a list of Subversion Repository links or also all the Subversion Repository attributes.|enum (links, all)|
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlsvnviewlist,XmlSvnViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/subversions
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "subversions" : [ {
    "command-path" : "c:/vcrs/svn/bin",
    "description" : "description",
    "fetch-meta-properties" : true,
    "id" : "urn:alm:viewName:1:1",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "name" : "SVNRepository",
    "password" : "********",
    "repository-layout" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "repository-url" : "file:///C:/almdemo/repository/svn/",
    "tags-directory" : "tags",
    "timeout" : 30,
    "trunk-directory" : "trunk",
    "type" : "svn",
    "user-id" : "svnuser"
  } ],
  "total" : 0
}
----


[[_getbyoidusingget_6]]
==== Get Subversion Repository
....
GET /subversions/{id}
....


===== Description
Get the details of a specific Subversion Repository.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Subversion Repository to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlsvnview,XmlSvnView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/subversions/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "command-path" : "c:/vcrs/svn/bin",
  "description" : "description",
  "fetch-meta-properties" : true,
  "id" : "urn:alm:viewName:1:1",
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "name" : "SVNRepository",
  "password" : "********",
  "repository-layout" : {
    "id" : 0,
    "link" : {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    },
    "text" : "Value for 0"
  },
  "repository-url" : "file:///C:/almdemo/repository/svn/",
  "tags-directory" : "tags",
  "timeout" : 30,
  "trunk-directory" : "trunk",
  "type" : "svn",
  "user-id" : "svnuser"
}
----


[[_getprojectsbysubversionoidusingget]]
==== Get Projects connected to a Subversion Repository.
....
GET /subversions/{id}/projects
....


===== Description
Get the projects connected to a specific Subversion Repository.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the Subversion Repository to retrieve the Projects for.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlprojectviewlist,XmlProjectViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/subversions/1/projects
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "projects" : [ {
    "admingroup" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "archived" : true,
    "buildscript" : "build.xml",
    "deployscript" : "deploy.xml",
    "description" : "description",
    "id" : "urn:alm:viewName:1:1",
    "issuetrackingsystem" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "locked" : true,
    "name" : "name",
    "projecttype" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Value for 0"
    },
    "usergroup" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "vcr" : {
      "id" : 0,
      "link" : {
        "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
        "rel" : "LinkRel",
        "title" : "Title"
      },
      "text" : "Other Resource"
    },
    "vcr-projectname" : "Customers"
  } ],
  "total" : 0
}
----


[[_user_groups_resource]]
=== User Groups
This resource represents User Groups. Use it to obtain details of the existing User Groups.


[[_getallusingget_8]]
==== Get User Groups paginated
....
GET /usergroups
....


===== Description
Get a paginated list of User Groups, optionally filtered by name, description or types.
 Sorting can be done by name or type.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**description** +
__optional__|The description to filter the User Groups by.|string|
|**Query**|**name** +
__optional__|The name to filter the User Groups by.|string|
|**Query**|**page** +
__optional__|The page to retrieve, defaulted to 1.|string|`"1"`
|**Query**|**pagesize** +
__optional__|The page size to retrieve, defaulted to 10.|string|`"10"`
|**Query**|**sortcolumn** +
__optional__|The attribute to sort the result by, check the endpoint description for the possible values.|string|
|**Query**|**sortdirection** +
__optional__|The sort direction to order the result, defaulted to ascending.|enum (desc, descending, true, asc, ascending, false)|`"asc"`
|**Query**|**type** +
__optional__|The type to filter the User Groups by (0=external; 1=internal).|enum (0, 1)|
|**Query**|**view** +
__optional__|Whether to show only a list of User Group links or also all the User Group attributes.|enum (links, all)|
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlusergroupviewlist,XmlUserGroupViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/usergroups
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0,
  "usergroups" : [ {
    "description" : "description",
    "id" : "urn:alm:viewName:1:1",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "name" : "ALM Administrator",
    "type" : 0
  } ]
}
----


[[_getbyoidusingget_7]]
==== Get User Group
....
GET /usergroups/{id}
....


===== Description
Get the details of a specific User Group.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the User Group to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlusergroupview,XmlUserGroupView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/usergroups/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "description" : "description",
  "id" : "urn:alm:viewName:1:1",
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "name" : "ALM Administrator",
  "type" : 0
}
----


[[_getusersbyusergroupoidusingget]]
==== Get Users connected to a User Group.
....
GET /usergroups/{id}/users
....


===== Description
Get the users connected to a specific User Group.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the User Group to retrieve the Users for.|integer (int32)
|**Query**|**view** +
__optional__|Whether to show only a list of User links that are connected to a User Group or also all the User attributes.|enum (links, all)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmluserviewlist,XmlUserViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/usergroups/1/users
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0,
  "users" : [ {
    "archived" : true,
    "browserID" : "string",
    "description" : "description",
    "email-address" : "user@example.com",
    "id" : "urn:alm:viewName:1:1",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "locale" : "en",
    "location" : "UserHouse",
    "login-date" : "1574353976919",
    "login-hostIP" : "0:0:0:0:0:0:0:1",
    "login-hostname" : "localhost",
    "mobile-number" : "+32 (0)11 22 33 44",
    "name" : "User",
    "reserved" : true,
    "tel-number" : "+32 (0)11 22 33 44",
    "user-id" : "user"
  } ]
}
----


[[_users_resource]]
=== Users
This resource represents Users. Use it to obtain details of the existing Users.


[[_getallusingget_9]]
==== Get Users paginated
....
GET /users
....


===== Description
Get a paginated list of Users, optionally filtered by name, userid or connection.
 Sorting can be done by name or userid.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|Type|Name|Description|Schema|Default
|**Query**|**connectedusers** +
__optional__|Whether to show a list of Users that are currently connected to Kobee.|boolean|
|**Query**|**name** +
__optional__|The name to filter the User by.|string|
|**Query**|**page** +
__optional__|The page to retrieve, defaulted to 1.|string|`"1"`
|**Query**|**pagesize** +
__optional__|The page size to retrieve, defaulted to 10.|string|`"10"`
|**Query**|**sortcolumn** +
__optional__|The attribute to sort the result by, check the endpoint description for the possible values.|string|
|**Query**|**sortdirection** +
__optional__|The sort direction to order the result, defaulted to ascending.|enum (desc, descending, true, asc, ascending, false)|`"asc"`
|**Query**|**userid** +
__optional__|The userid to filter the Users by.|string|
|**Query**|**view** +
__optional__|Whether to show only a list of User links or also all the User attributes.|enum (links, all)|
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmluserviewlist,XmlUserViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/users
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0,
  "users" : [ {
    "archived" : true,
    "browserID" : "string",
    "description" : "description",
    "email-address" : "user@example.com",
    "id" : "urn:alm:viewName:1:1",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "locale" : "en",
    "location" : "UserHouse",
    "login-date" : "1574353976919",
    "login-hostIP" : "0:0:0:0:0:0:0:1",
    "login-hostname" : "localhost",
    "mobile-number" : "+32 (0)11 22 33 44",
    "name" : "User",
    "reserved" : true,
    "tel-number" : "+32 (0)11 22 33 44",
    "user-id" : "user"
  } ]
}
----


[[_getbyoidusingget_8]]
==== Get User
....
GET /users/{id}
....


===== Description
Get the details of a specific User.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the User to retrieve.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmluserview,XmlUserView>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/users/1
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "archived" : true,
  "browserID" : "string",
  "description" : "description",
  "email-address" : "user@example.com",
  "id" : "urn:alm:viewName:1:1",
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "locale" : "en",
  "location" : "UserHouse",
  "login-date" : "1574353976919",
  "login-hostIP" : "0:0:0:0:0:0:0:1",
  "login-hostname" : "localhost",
  "mobile-number" : "+32 (0)11 22 33 44",
  "name" : "User",
  "reserved" : true,
  "tel-number" : "+32 (0)11 22 33 44",
  "user-id" : "user"
}
----


[[_getusergroupsforuserusingget]]
==== Get User Groups the User is connected to.
....
GET /users/{id}/usergroups
....


===== Description
Get the User Groups that are connected to a specific User.


===== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Path**|**id** +
__required__|The identifier of the User to retrieve the User Groups for.|integer (int32)
|===


===== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|OK|<<RESTAPI_Definitions.adoc#_xmlusergroupviewlist,XmlUserGroupViewList>>
|**401**|Unauthorized|No Content
|**403**|Forbidden|No Content
|**404**|Not Found|No Content
|===


===== Example HTTP request

====== Request path
----
/users/1/usergroups
----


===== Example HTTP response

====== Response 200
[source,json]
----
{
  "count" : 0,
  "links" : [ {
    "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
    "rel" : "LinkRel",
    "title" : "Title"
  } ],
  "page" : 0,
  "pagesize" : 0,
  "total" : 0,
  "usergroups" : [ {
    "description" : "description",
    "id" : "urn:alm:viewName:1:1",
    "links" : [ {
      "href" : "http://alm.example.local:8080/alm/rest/v1/link/href/1",
      "rel" : "LinkRel",
      "title" : "Title"
    } ],
    "name" : "ALM Administrator",
    "type" : 0
  } ]
}
----






